### ISSUE TITLE
Mouse hover sometimes incorrect

### ISSUE THREAD

**Issue by landcraft** [kkYrusobad/kkYrusobad.github.io#1]
https://user-images.githubusercontent.com/73437748/119705273-1f4fff00-be8b-11eb-8830-0218355d85ec.mp4

Please see attached video screenshot

**Comment by kkYrusobad** [comment]
I'm sorry but I am unable to see the said attached document. Please take another look at the issue.

**Comment by landcraft** [comment]
> I'm sorry but I am unable to see the said attached document. Please take another look at the issue.

updated comment - problem with the upload..

**Comment by kkYrusobad** [comment]
hmm, yes I also had the same problem sometime earlier. This supposedly happens due to icon scope overflow, meaning icon's focus area overall overflows outside its wanted area because of faulty svg code.
try changing it to other icons or maybe troubleshoot the existing one.
refer to commit on the main repo involving this, I fixed this same problem on my instance.

**Comment by landcraft** [comment]
fixed in mine by making sure all svg width and height at 128
